services:
  openaudible:
    image: openaudible/openaudible:latest
    restart: unless-stopped
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:unconfined
    volumes:
      - ${APP_DATA_DIR}/data:/config/OpenAudible
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ:-Europe/Berlin}
      - OA_BETA=${OA_BETA:-false}
      - DWEBKIT_DISABLE_DMABUF_RENDERER=1
      - DWEBKIT_DISABLE_COMPOSITING_MODE=1
      - DWEBKIT_FORCE_SOFTWARE_RENDERING=1
      - DGDK_GL=disable
      - KASM_AUDIO_ENABLED=1
      - OA_KIOSK=true
      - oa_internal_browser=true
    x-runtipi:
      is_main: true
      internal_port: 3000

x-runtipi:
  schema_version: 2
